### ISSUE TITLE
100% reads filtered out

### ISSUE THREAD

**Issue by mbaddoo** [PeeperLab/XenofilteR#10]
Hello-
Thanks for this program! I ran into the same problem as ChelseaCHENX, with 100% of human reads filtered out. Has this issue been resolved? If so, can you kindly point me to a solution, please?
Thank you!
Melody

**Comment by PeeperLab2** [comment]
Dear Melody,

Thank you for using XenofilteR.
The previous issue was solved by adding the NM-tag in the bam file when mapping with STAR.

Please check this section in the XenofilteR documentation:
https://github.com/PeeperLab/XenofilteR - section with header “Important note for STAR users”.

Please check if this solves your problem. If not, let me know and specify what kind of data you have and provide the log files so we can solve your specific issue.

Good luck! Kind regards, Oscar



Oscar Krijgsman, PhD
Postdoctoral research fellow
Division of Molecular Oncology & Immunology
The Netherlands Cancer Institute
Plesmanlaan 121
1066 CX Amsterdam, the Netherlands




On 19 Sep 2019, at 06:15, mbaddoo <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello-
Thanks for this program! I ran into the same problem as ChelseaCHENX, with 100% of human reads filtered out. Has this issue been resolved? If so, can you kindly point me to a solution, please?
Thank you!
Melody

**Comment by mbaddoo** [comment]
Hello Oscar-

Thanks so much for your speedy reply.  Indeed, I did add the 'NM' tag as specified.  See a sample from aligned file below:

V300029302L1C003R0420856074 339 chr1 631204 3 90M10S = 631092 -202 CAGGCAACCTTTTAGGTAACGACCACATCTACAACGTTAACGTCACAGACCATGCATTTGTAATAATCTTCTTCATAGTAATACCCATCATAATCGGAGG 7F?FAG>;EF5*?BGFE<DG,161FB2/*G6;A31E:;F*BD&;F>></5>F3>D@)53G<GGFD<*1B(F/+BBABGDFCDFFFGFF3;GGF;37@F>F NM:i:3
V300029302L1C006R0150931350 339 chr1 631204 3 90M10S = 631104 -190 CAGGCAACCTTCTAGGTAACGACCACATCTACAACGTTATCGTCACAGCACATGCATTTGTAATAATCTTCTTCATAGTAATACCCATCATAATCGGAGG FEFCEA/:FEBF=F?<C2FFFB5FFEFFFG:DFE=EDFDDDBEA>FF:>(CEFDFB9EFFGF6FAF<F>>6EFEEEF8GF=?;?5FFFFB@=F?*BFEF4 NM:i:1
V300029302L2C003R0620899705 339 chr1 631204 3 72M28S = 631103 -173 CAGGCAACCTTCTAGGTAACGACCACATCTGCAACGTTATCGTCACACGCCATAGATTTGTTCTAATATTCTCCGTAGTCAGCATGATCATAGTCGGAGG AFFFFFCFFEBF;FFFEDAFFD?FFFFEFAFFFFDFEGFFFFFFFFFGFCEFCG(FFFAFFD(FFFBEBFFF5F5FFFC/FFFFFGFDFFFF-AFFFFFF NM:i:8


Reads were aligned to reference genome using STAR as follows:

STAR --genomeDir /PATH/starGenomes/1_hg38_chr_labels --clip5pNbases 10 --readFilesCommand zcat --readFilesIn ${prefix}_1.fq.gz ${prefix}_2.fq.gz --outFileNamePrefix ${prefix}_hg38 --runThreadN 10 --outSAMattributes NM --outSAMtype BAM SortedByCoordinate

Might you have any other ideas about why I am experiencing this issue?  I used STAR because it's fast...should I try another aligner?

Again, thank you so much for this program and for your speedy reply.  I look forward to hearing from you.

Best-

Melody 

________________________________________

**Comment by PeeperLab2** [comment]
Hi Melody,

No, you do not have to use another aligner. STAR works very well and is the standard aligner in our lab for RNAseq.
After looking at your STAR command I think I understand what happens and why you do not have any reads in the filtered output.

XenofilteR is based on the edit distance of a read to the human and to the mouse reference genome. This edit-distance is calculated based on the number of mismatches (NM-tag) and the number of soft-clipped base-pairs combined. A read gets assigned to the reference genome with the lowest edit-distance. But, in addition to this classification there is another filter in XenofilteR: Sequence reads with an edit-distance higher than set threshold (default: MM-threshold = 4) will not be included in the final output.

You used the —clip5pNbases parameter to soft clip 10 bases from your sequence read. I assume you do this to exclude the primer/linker sequence or something. However, as explained above this will automatically result in a larger edit-distance than the threshold and none of the reads will make it to the final output.

There are 2 options to solve this:

1- Clip the 10 bp from your sequence reads with another tool. Next map with STAR to human and mouse using the 90bp reads.
2- Change the settings of XenofilteR. I would set the MM-threshold to 10+6 (your have long reads and the default was set for samples with 75bp reads, therefore I would go a little higher than 4). I would also set the Unmapped_penalty to 10+6 = 16
XenofilteR(sample.list, destination.folder = "./", bp.param = bp.param, output.names, mm_threshold = 16, Unmapped_penalty = 16)

Theoretically this should solve the issue with the soft-clips. But I have no experience with STAR to soft clip sequence reads and have no idea how good this work around will be. Using solution 1 would be the saved option. I haven’t checked but maybe you can also hard-clip the reads using STAR?


Hope this works for you. Let me know what you have tried and how the data looks and feel free to send another email when in doubt.

Kind regards, Oscar








On 19 Sep 2019, at 15:30, mbaddoo <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello Oscar-

Thanks so much for your speedy reply. Indeed, I did add the 'NM' tag as specified. See a sample from aligned file below:

V300029302L1C003R0420856074 339 chr1 631204 3 90M10S = 631092 -202 CAGGCAACCTTTTAGGTAACGACCACATCTACAACGTTAACGTCACAGACCATGCATTTGTAATAATCTTCTTCATAGTAATACCCATCATAATCGGAGG 7F?FAG>;EF5*?BGFE<DG,161FB2/*G6;A31E:;F*BD&;F>></5>F3>D@)53G<GGFD<*1B(F/+BBABGDFCDFFFGFF3;GGF;37@F>F NM:i:3
V300029302L1C006R0150931350 339 chr1 631204 3 90M10S = 631104 -190 CAGGCAACCTTCTAGGTAACGACCACATCTACAACGTTATCGTCACAGCACATGCATTTGTAATAATCTTCTTCATAGTAATACCCATCATAATCGGAGG FEFCEA/:FEBF=F?<C2FFFB5FFEFFFG:DFE=EDFDDDBEA>FF:>(CEFDFB9EFFGF6FAF<F>>6EFEEEF8GF=?;?5FFFFB@=F?*BFEF4 NM:i:1
V300029302L2C003R0620899705 339 chr1 631204 3 72M28S = 631103 -173 CAGGCAACCTTCTAGGTAACGACCACATCTGCAACGTTATCGTCACACGCCATAGATTTGTTCTAATATTCTCCGTAGTCAGCATGATCATAGTCGGAGG AFFFFFCFFEBF;FFFEDAFFD?FFFFEFAFFFFDFEGFFFFFFFFFGFCEFCG(FFFAFFD(FFFBEBFFF5F5FFFC/FFFFFGFDFFFF-AFFFFFF NM:i:8


Reads were aligned to reference genome using STAR as follows:

STAR --genomeDir /PATH/starGenomes/1_hg38_chr_labels --clip5pNbases 10 --readFilesCommand zcat --readFilesIn ${prefix}_1.fq.gz ${prefix}_2.fq.gz --outFileNamePrefix ${prefix}_hg38 --runThreadN 10 --outSAMattributes NM --outSAMtype BAM SortedByCoordinate

Might you have any other ideas about why I am experiencing this issue? I used STAR because it's fast...should I try another aligner?

Again, thank you so much for this program and for your speedy reply. I look forward to hearing from you.

Best-

Melody Cunningham Baddoo
Sr. Research Scientist
Tulane Cancer Center
Cancer Crusaders Next Generation Sequence Analysis Core/UF-Tulane NIH P01 core B
1700 Tulane Avenue, Room 810
New Orleans, LA 70112
504-988-1345
mbaddoo@tulane.edu<mailto:mbaddoo@tulane.edu>


________________________________________

**Comment by mbaddoo** [comment]
Hi Oscar-
I removed the --clip5pNbases parameter (I didn't need it anyway) and re-aligned the samples.  Happy to report that XenofilteR worked beautifully.  
Many thanks for your assistance!
Best-
Melody
