### ISSUE TITLE
Can XenofilteR be used for single cell RNA seq?

### ISSUE THREAD

**Issue by pikapika505** [PeeperLab/XenofilteR#13]
Will I be able to filter out mouse reads from sc RNA-seq using your tool? 

I aligned my fastq files separately to human and mouse references getting 2 bam files. My goal is to get rid of mouse cells and analyze the remaining cells. 

thank you!

**Comment by PeeperLab2** [comment]
Interesting question.
I have never used it for scSeq but XenofilteR will distinguish between reads from mouse and human origin if you have 2 bam files.

And you could add another level by checking the number of sequence reads that are classified as human and mouse (will be 1% vs 99% or vise versa) and identify all cells that are from mouse, making the filtering even better. Or maybe simply count number of sequence reads after filtering per cell and remove all cells with very few reads.

Hope it works for you! If you have any questions feel free to send another email.

Best Oscar


On 29 Jun 2020, at 17:24, YuliaInn <notifications@github.com<mailto:notifications@github.com>> wrote:



Will I be able to filter out mouse reads from sc RNA-seq using your tool?

I aligned my fastq files separately to human and mouse references getting 2 bam files. My goal is to get rid of mouse cells and analyze the remaining cells.

thank you!

**Comment by pikapika505** [comment]
thank you for your prompt reply. I actually ran Xenofilter on hose 2 files. But when I tried to quantify the filtered bam file in order to get the expression matrix, it gave me a matrix without cell columns. I used [featureCounts from this tutorial ](https://scrnaseq-course.cog.sanger.ac.uk/website/construction-of-expression-matrix.html#reads-quantification)

**Comment by PeeperLab2** [comment]
Hi,

And this function does give you the matrix with cell columns when running on the original bam file?
XenofilteR should leave the bam file exactly like its original minus the mouse reads. I would expect behaviour of follow-up tools to be exactly as for for the pre-XenofilteR files.




On 29 Jun 2020, at 17:45, YuliaInn <notifications@github.com<mailto:notifications@github.com>> wrote:



thank you for your prompt reply. I actually ran Xenofilter on hose 2 files. But when I tried to quantify the filtered bam file in order to get the expression matrix, it gave me a matrix without cell columns. I used featureCounts from this tutorial <https://scrnaseq-course.cog.sanger.ac.uk/website/construction-of-expression-matrix.html#reads-quantification>

**Comment by pikapika505** [comment]
I guess the problem was that my data did not contain UMIs. I think my analysis should be entirely done in cellranger instead.
But is there any way to see the percentage of mouse contaminated reads? I am not familiar with bam files. Is there a software to open it? I thought we could just ignore mouse cells if there are not too many of them in our sample.

**Comment by PeeperLab2** [comment]
Hi,

There are many tools to work with Bam files. Samtools is most used and much can be done in Rsamtools if you would like to stay in R.
Others have probably solved your issue already. I would start by looking into scSeq papers of PDX and see how they have solved the mouse cell issue. I can imagine that there are genes that are expressed specifically in mouse or human, you might be able to use this to distinguish human from mouse cells.

Good luck with the analysis! Best Oscar




On 1 Jul 2020, at 22:41, YuliaInn <notifications@github.com<mailto:notifications@github.com>> wrote:



I guess the problem was that my data did not contain UMIs. I think my analysis should be entirely done in cellranger instead.
But is there any way to see the percentage of mouse contaminated reads? I am not familiar with bam files. Is there a software to open it? I thought we could just ignore mouse cells if there are not too many of them in our sample.

**Comment by pikapika505** [comment]
thank you very much!
