### ISSUE TITLE
Total number of filtered reads

### ISSUE THREAD

**Issue by wrongbong** [PeeperLab/XenofilteR#14]
Hello!
I have been using XENOfilter to filter out mouse reads from a PDX sample. After some checking, I noticed that the script basically applies the filter only on the reads which are mapped to the graft (human) genome and is a primary alignment.  All the unmapped reads are dumped out from the file (Filtered file) as well.  

Now, what I want to do is measure the amount of mouse cell infiltration in each PDX sample. As a proxy for that, I want to use the percentage of filtered reads. Now, if I use the percentage of filtered reads from the log file, I get only the percentage of filtered reads which were already mapped to the human genome and were primary alignments. If a read was purely coming from a mouse cell and not getting mapped to the human genome, that read wouldn't show up in the filtered reads in the log file.

In that case, would it be better to simply take the number of mouse reads as (number of unmapped reads + number of filtered reads from the log file) and then divide by the total number of reads to get the percentage?

Thanks,

**Comment by RoelKluin** [comment]
This a late reply to an old question, sorry about that, but in any case you or anyone else wants to try this, It is possible to deduce the filtered reads from the filtered plus unfiltered bam files (for the same species!). It requires some computer memory because the filtering is based on the read names, and something like this, untested, though:
```bash
(samtools view -H $filtered_bam;
samtools view $filtered_bam | cut -f 1 | grep -v -F -f /dev/stdin <(samtools view $unfiltered_bam)) |
samtools view -b -> $removed_reads_bam
```
Side note, if you order the reads on readname, then you can filter with little memory requirements. It requires some scripting skills, though.
