### ISSUE TITLE
Xenofilter for other species (non-human)

### ISSUE THREAD

**Issue by dongwankimlab** [PeeperLab/XenofilteR#31]
Hi, Thank yoy for the great tool.

Can I use it for other species? For example, I want to separate non-human primate (NHP) reads and mouse/rat reads.
Also, if reference genome of NHP is incomplete and contains many Ns in coding region, would XenofilteR give a lot of penalty on NHP reads? Can I apply XenofilteR on incomplete reference genome?

Thank you in advance!

**Comment by RoelKluin** [comment]
XenofilteR can be used for other species. Reads derived from sequence regions not yet included in the reference will not be aligned to the reference of this species and will be filtered. 

To retrieve such reads, you could reverse the filtering and isolate unmapped reads or reads with large clips in the filtered rat alignments. Then those reads could maybe be assembled.

Filtering of reads may also occur if the reference contains several Ns, which aligners may interpret as an A. Every non matching base is then penalized. If you are afraid to lose those reads, you could elevate the mismatch threshold and unmapped penalty to n and n+4, or disable the first by setting it to read length. Even though the mismatches due to Ns, reads may align better to graft if originating thereof than to host and remain in the filtered data with those settings.

**Comment by dongwankimlab** [comment]
I appreciate your detailed explanation!
